baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'petruzzellialessandro'

theme = "personal-web"

[params.intro]
  main = "Hi, I'm Alessandro"
  sub = "I'm a PhD Student in Computer Science"

[params.main]
  latestPublishHeader = "My Latest Project"

[taxonomies]
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404
  rendererSafe = false # set to true if wish to remove the unsafe renderer setting below (recommended). Titles will not be run through markdownify

[params.notFound]
  myImage = "/images/notFound.jpeg" 
  h1 = 'Not Found!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = "/images/Botticelli.jpg"
  logo = "images/aleFace.jpg"

[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/petruzzellialessandro"
  twitter = "https://twitter.com/AlePetruzzelli"
  linkedin = "https://www.linkedin.com/in/alessandro-petruzzelli-3b5b3b212/"

[params.contact]
  email = "alessandro.petruzzelli@uniba.it"
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "Curriculum"
  name = "Curriculum"
  title = "Curriculum"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "Projects"
  name = "Projects"
  title = "Projects"
  url = "/portfolio/"
  weight = -110

[[menu.main]]
  identifier = "Notes"
  name = "Notes"
  title = "Notes"
  url = "/notes/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true